# coding=utf-8
"""Multi-table TableRAG agent for DataBench."""

from __future__ import annotations

import ast
import json
import os
import hashlib
import fcntl
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from agent.rag_agent import TableRAGAgent
from utils.execute import parse_code_from_string, python_repl_ast
from utils.utils import infer_dtype, is_numeric, read_json
from prompts.wtq import tablerag_multi_cmoney_solve_table_prompt


_QUERY_EXPANSION_CACHE_VERSION = 1


def unique_keep_order(values: list[str]) -> list[str]:
    seen = set()
    output = []

    for value in values:
        if value not in seen:
            seen.add(value)
            output.append(value)

    return output


def format_databench_answer(value: Any) -> str:
    """Convert parsed JSON answer to DataBench response text."""

    if isinstance(value, bool):
        return "True" if value else "False"

    if isinstance(value, list):
        return json.dumps(
            value,
            ensure_ascii=False,
            separators=(", ", ": "),
        )

    if value is None:
        return ""

    return str(value).strip()


class TableRAGMultiAgent(TableRAGAgent):
    def __init__(
        self,
        candidate_k: int = 10,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.candidate_k = candidate_k

    def generate_query_list(
        self,
        prompt: str,
        remove_numeric: bool = False,
        max_attempt: int = 3,
    ) -> list[str]:
        """Generate query expansion once for all candidate tables."""

        for _ in range(max_attempt):
            text = self.query(prompt)

            try:
                start = text.find("[")
                end = text.rfind("]") + 1

                if start < 0 or end <= start:
                    raise ValueError(
                        f"No JSON list found: {text}"
                    )

                queries = read_json(text[start:end])

                if not isinstance(queries, list):
                    raise TypeError(
                        "Expansion output is not a list."
                    )

                queries = [
                    str(query).strip()
                    for query in queries
                    if str(query).strip()
                ]

                if remove_numeric:
                    queries = [
                        query
                        for query in queries
                        if not is_numeric(query)
                    ]

                return unique_keep_order(queries)

            except Exception:
                if self.verbose:
                    print(
                        "### Query expansion parse error:",
                        text,
                    )

        return []

    def _expansion_cache_identity(
        self,
        prompt: str,
        remove_numeric: bool,
        expansion_type: str,
    ) -> tuple[str, dict[str, Any]]:
        """
        Build a cache key from the exact expansion prompt and model settings.

        This intentionally includes model_name so different reasoning-model
        experiments do not silently share query expansions generated by
        another model.
        """
        identity = {
            "version": _QUERY_EXPANSION_CACHE_VERSION,
            "expansion_type": str(expansion_type),
            "prompt": str(prompt),
            "remove_numeric": bool(remove_numeric),
            "model_name": str(getattr(self, "model_name", "")),
            "temperature": getattr(self, "temperature", None),
            "top_p": getattr(self, "top_p", None),
            "max_tokens": getattr(self, "max_tokens", None),
            "reasoning_effort": getattr(
                self,
                "reasoning_effort",
                None,
            ),
        }

        raw = json.dumps(
            identity,
            ensure_ascii=False,
            sort_keys=True,
            default=str,
            separators=(",", ":"),
        ).encode("utf-8")

        digest = hashlib.sha256(raw).hexdigest()
        return digest, identity

    @staticmethod
    def _expansion_usage_snapshot(agent) -> dict[str, int]:
        """
        Snapshot usage counters that may be maintained by the base agent.
        """
        names = [
            "total_input_token_count",
            "total_output_token_count",
            "total_reasoning_token_count",
            "total_api_token_count",
        ]

        snapshot = {}
        for name in names:
            value = getattr(agent, name, None)
            if isinstance(value, (int, np.integer)):
                snapshot[name] = int(value)

        return snapshot

    @staticmethod
    def _expansion_usage_delta(
        before: dict[str, int],
        after: dict[str, int],
    ) -> dict[str, int]:
        delta = {}
        for name, after_value in after.items():
            before_value = before.get(name, 0)
            delta[name] = int(after_value) - int(before_value)
        return delta

    @staticmethod
    def _apply_cached_expansion_usage(
        agent,
        usage_delta: dict[str, Any],
    ) -> None:
        """
        Re-add the token usage from the original expansion generation.

        This keeps experiment token accounting comparable even though the
        cached run does not actually call the LLM again.
        """
        if not isinstance(usage_delta, dict):
            return

        for name, delta in usage_delta.items():
            current = getattr(agent, name, None)

            if (
                isinstance(current, (int, np.integer))
                and isinstance(delta, (int, np.integer))
            ):
                setattr(agent, name, int(current) + int(delta))

    def generate_query_list_cached(
        self,
        prompt: str,
        remove_numeric: bool,
        expansion_type: str,
        max_attempt: int = 3,
    ) -> list[str]:
        """
        Persistent query-expansion cache.

        Lookup order:
            disk cache -> LLM generation -> save to disk

        One JSON file is used per expansion key. A per-key Linux file lock
        prevents duplicate LLM calls when multiple workers encounter the
        same expansion simultaneously.
        """
        digest, identity = self._expansion_cache_identity(
            prompt=prompt,
            remove_numeric=remove_numeric,
            expansion_type=expansion_type,
        )

        db_root = Path(getattr(self, "db_dir", None) or "db")
        cache_dir = (
            db_root
            / f"query_expansion_cache_v{_QUERY_EXPANSION_CACHE_VERSION}"
        )
        cache_dir.mkdir(parents=True, exist_ok=True)

        cache_path = cache_dir / f"{expansion_type}_{digest}.json"
        lock_path = cache_path.with_suffix(cache_path.suffix + ".lock")

        with lock_path.open("a+", encoding="utf-8") as lock_fp:
            fcntl.flock(lock_fp.fileno(), fcntl.LOCK_EX)

            try:
                # Re-check only after acquiring the lock.
                if cache_path.exists():
                    try:
                        with cache_path.open(
                            "r",
                            encoding="utf-8",
                        ) as fp:
                            saved = json.load(fp)

                        if (
                            isinstance(saved, dict)
                            and saved.get("identity") == identity
                            and isinstance(saved.get("queries"), list)
                        ):
                            queries = [
                                str(q).strip()
                                for q in saved["queries"]
                                if str(q).strip()
                            ]

                            self._apply_cached_expansion_usage(
                                self,
                                saved.get("usage_delta", {}),
                            )

                            if self.verbose:
                                print(
                                    "Query expansion disk cache hit: "
                                    f"{expansion_type}"
                                )

                            return queries

                        if self.verbose:
                            print(
                                "Query expansion cache stale: "
                                f"{expansion_type}; regenerate"
                            )

                    except Exception as exc:
                        if self.verbose:
                            print(
                                "Query expansion cache load failed: "
                                f"{expansion_type} | "
                                f"{type(exc).__name__}: {exc}; regenerate"
                            )

                    try:
                        cache_path.unlink()
                    except OSError:
                        pass

                if self.verbose:
                    print(
                        "Generate query expansion via LLM: "
                        f"{expansion_type}"
                    )

                before = self._expansion_usage_snapshot(self)

                queries = self.generate_query_list(
                    prompt=prompt,
                    remove_numeric=remove_numeric,
                    max_attempt=max_attempt,
                )

                after = self._expansion_usage_snapshot(self)
                usage_delta = self._expansion_usage_delta(
                    before,
                    after,
                )

                # Do not persist an empty result. A transient API/parse
                # failure should be retried on the next run.
                if not queries:
                    return queries

                payload = {
                    "identity": identity,
                    "queries": queries,
                    "usage_delta": usage_delta,
                }

                tmp_path = cache_path.with_name(
                    cache_path.name + f".tmp.{os.getpid()}"
                )

                try:
                    with tmp_path.open(
                        "w",
                        encoding="utf-8",
                    ) as fp:
                        json.dump(
                            payload,
                            fp,
                            ensure_ascii=False,
                            indent=2,
                        )
                        fp.flush()
                        os.fsync(fp.fileno())

                    os.replace(tmp_path, cache_path)

                finally:
                    if tmp_path.exists():
                        try:
                            tmp_path.unlink()
                        except OSError:
                            pass

                return queries

            finally:
                fcntl.flock(lock_fp.fileno(), fcntl.LOCK_UN)

    def retrieve_one_table(
        self,
        table_id: str,
        df: pd.DataFrame,
        column_queries: list[str],
        cell_queries: list[str],
    ) -> tuple[str, list[str], list[str]]:
        """Run original TableRAG retrieval independently on one table."""

        self.retriever.init_retriever(table_id, df)

        schema_docs: list[str] = []

        for query in column_queries:
            schema_docs.extend(
                self.retriever.retrieve_schema(query)
            )

        cell_docs: list[str] = []

        for query in cell_queries:
            cell_docs.extend(
                self.retriever.retrieve_cell(query)
            )

        schema_docs = unique_keep_order(schema_docs)
        cell_docs = unique_keep_order(cell_docs)

        evidence_parts = [
            "Schema Retrieval Queries: "
            + ", ".join(column_queries),
            "Schema Retrieval Results:",
            "\n".join(schema_docs) if schema_docs else "(none)",
            "",
            "Cell Retrieval Queries: "
            + ", ".join(cell_queries),
            "Cell Retrieval Results:",
            "\n".join(cell_docs) if cell_docs else "(none)",
        ]

        return (
            "\n".join(evidence_parts),
            schema_docs,
            cell_docs,
        )


    @staticmethod
    def parse_multi_final(
        text: str,
    ) -> tuple[dict[str, Any] | None, str]:
        """Parse both labeled and bare multi-table final JSON."""

        candidate = text.strip()
        lower_candidate = candidate.lower()

        # Standard expected format:
        # Final Answer: {"table_source": "df2", "answer": true}
        if "final answer:" in lower_candidate:
            position = lower_candidate.rfind("final answer:")
            candidate = candidate[
                position + len("final answer:"):
            ].splitlines()[0].strip()

        # Be tolerant if the model explicitly writes Thought:
        elif lower_candidate.startswith("thought:"):
            candidate = candidate[
                len("thought:"):
            ].strip()

        # Remove optional Markdown fences.
        if candidate.startswith("```"):
            candidate = candidate.strip("`").strip()

            if candidate.lower().startswith("json"):
                candidate = candidate[4:].strip()

        payload = None

        try:
            payload = json.loads(candidate)
        except json.JSONDecodeError:
            try:
                payload = ast.literal_eval(candidate)
            except (ValueError, SyntaxError):
                payload = None

        if (
            isinstance(payload, dict)
            and "table_source" in payload
            and "answer" in payload
        ):
            return payload, candidate

        return None, candidate

    def solver_loop_multi(
        self,
        dfs: dict[str, pd.DataFrame],
        prompt: str,
    ) -> tuple[
        str,
        str | None,
        int,
        str,
        str,
    ]:
        """ReAct loop with df1 ... dfK available to Python."""

        if self.verbose:
            print(prompt, end="")

        memory: dict[str, Any] = {}
        n_iter = self.max_depth
        solution = ""
        init_prompt = prompt
        text = ""

        for i in range(self.max_depth):
            solution += "Thought: "
            current_prompt = init_prompt + solution

            text = self.query(current_prompt).strip()
            solution += text

            if self.verbose:
                print("Thought: " + text)

            # gpt-5.6-sol may output the final JSON directly,
            # without the literal "Final Answer:" prefix.
            terminal_payload, _ = self.parse_multi_final(
                text
            )

            if (
                terminal_payload is not None
                or self.is_terminal(text)
            ):
                n_iter = i + 1
                break

            if "Action:" not in text:
                observation = "Error: no Action provided."

            else:
                code = parse_code_from_string(
                    text.split("Action:")[-1].strip()
                )

                # GPT 偶爾會把整段 Python Action 包成字串。
                # 例如 Action: "df2['Age'].mean()"
                # 此時移除最外層引號後再執行真正的程式碼。
                try:
                    decoded_code = ast.literal_eval(code)

                    if isinstance(decoded_code, str):
                        code = decoded_code
                except (ValueError, SyntaxError):
                    pass

                # Put df1...dfK in both globals and locals.
                # This also supports list comprehensions.
                execution_globals = {
                    **globals(),
                    **dfs,
                    **memory,
                }

                observation, memory = python_repl_ast(
                    code,
                    custom_locals={**dfs},
                    custom_globals=execution_globals,
                    memory=memory,
                )

                if (
                    isinstance(observation, str)
                    and self.model.get_token_count(observation)
                    > self.model.context_limit
                ):
                    observation = (
                        "Observation is too long, "
                        "we cannot query the API."
                    )

                if observation == "":
                    observation = "success!"

            if "\n" in str(observation):
                observation = "\n" + str(observation)

            solution += f"\nObservation: {observation}\n"

            if self.verbose:
                print(f"Observation: {observation}")

        payload, raw_final = self.parse_multi_final(
            text
        )

        table_source = None
        answer_value: Any = raw_final

        if payload is not None:
            table_source = payload.get("table_source")
            answer_value = payload.get("answer", "")

        answer = format_databench_answer(answer_value)

        return (
            answer,
            table_source,
            n_iter,
            solution,
            raw_final,
        )

    def run(
        self,
        data: dict,
        sc_id: int = 0,
    ) -> dict:
        log_path = os.path.join(
            self.log_dir,
            "log",
            f'{data["id"]}-{sc_id}.json',
        )

        if os.path.exists(log_path) and self.load_exist:
            with open(log_path, encoding="utf-8") as fp:
                return json.load(fp)

        if self.verbose:
            print(
                "=" * 25
                + f' {data["id"]} '
                + "=" * 25
            )

        query = data.get("statement", data["question"])
        gold_table_id = data.get("gold_table_id")

        candidates = data.get("candidate_tables", [])
        candidates = candidates[:self.candidate_k]

        if not candidates:
            raise ValueError(
                f'No candidate tables for {data["id"]}'
            )

        # Generate expansion only once per question.
        column_prompt = self.get_prompt(
            "extract_column_prompt",
            table_caption="",
            query=query,
        )

        column_queries = self.generate_query_list_cached(
            prompt=column_prompt,
            remove_numeric=False,
            expansion_type="column",
        )

        cell_prompt = self.get_prompt(
            "extract_cell_prompt",
            table_caption="",
            query=query,
        )

        cell_queries = self.generate_query_list_cached(
            prompt=cell_prompt,
            remove_numeric=True,
            expansion_type="cell",
        )

        dfs: dict[str, pd.DataFrame] = {}
        source_map: dict[str, dict] = {}
        evidence_sections: list[str] = []

        all_retrieved_columns: dict[str, list[str]] = {}
        all_retrieved_cells: dict[str, list[str]] = {}

        for position, candidate in enumerate(
            candidates,
            start=1,
        ):
            df_name = f"df{position}"
            table_id = str(candidate["table_id"])
            table_path = Path(candidate["table_path"])
            rank = int(candidate.get("rank", position))
            score = candidate.get("score")

            if not table_path.exists():
                raise FileNotFoundError(
                    f"Candidate table not found: {table_path}"
                )

            df = pd.read_parquet(table_path)
            df = infer_dtype(df)

            dfs[df_name] = df

            source_map[df_name] = {
                "df_name": df_name,
                "rank": rank,
                "table_id": table_id,
                "title": candidate.get("title"),
                "table_path": str(table_path),
                "score": candidate.get("score"),
                "bm25_score": candidate.get("bm25_score"),
                "dense_score": candidate.get("dense_score"),
                "n_rows": int(df.shape[0]),
                "n_cols": int(df.shape[1]),
            }

            evidence, schema_docs, cell_docs = (
                self.retrieve_one_table(
                    table_id=table_id,
                    df=df,
                    column_queries=column_queries,
                    cell_queries=cell_queries,
                )
            )

            all_retrieved_columns[df_name] = schema_docs
            all_retrieved_cells[df_name] = cell_docs

            evidence_sections.append(
                "\n".join(
                    [
                        "=" * 72,
                        (
                            f"Candidate {df_name} | "
                            f"rank={rank} | "
                            f"table_id={table_id}"
                        ),
                        "=" * 72,
                        evidence,
                    ]
                )
            )

        candidate_table_map = "\n".join(
            (
                f'{df_name}: '
                f'table_id={info["table_id"]} | '
                f'title={info["title"]}'
            )
            for df_name, info in source_map.items()
        )

        table_evidence = "\n\n".join(evidence_sections)

        dataset_name = str(data.get("dataset", "")).strip().lower()
        is_cmoney = dataset_name == "cmoney"

        if is_cmoney:
            prompt = tablerag_multi_cmoney_solve_table_prompt.format(
                query=query,
                num_tables=len(dfs),
                candidate_table_map=candidate_table_map,
                table_evidence=table_evidence,
            )
        else:
            prompt = self.get_prompt(
                "solve_table_prompt",
                query=query,
                num_tables=len(dfs),
                candidate_table_map=candidate_table_map,
                table_evidence=table_evidence,
            )

        init_prompt_token_count = (
            self.model.get_token_count(prompt)
        )

        (
            answer,
            table_source,
            n_iter,
            solution,
            raw_final,
        ) = self.solver_loop_multi(dfs, prompt)

        selected_info = source_map.get(table_source)

        selected_table_id = (
            selected_info["table_id"]
            if selected_info
            else None
        )

        selected_rank = (
            selected_info["rank"]
            if selected_info
            else None
        )

        candidate_table_ids = [
            info["table_id"]
            for info in source_map.values()
        ]

        result = {
            "id": data["id"],
            "sc_id": sc_id,
            "query": query,
            "answer": answer,
            "label": data["label"],

            "raw_final_answer": raw_final,
            "table_source": table_source,
            "selected_table_id": selected_table_id,
            "selected_rank": selected_rank,
            "gold_table_id": gold_table_id,
            "selected_is_gold": (
                selected_table_id == gold_table_id
                if selected_table_id is not None
                else False
            ),
            "gold_in_candidates": (
                gold_table_id in candidate_table_ids
                if gold_table_id is not None
                else None
            ),

            "candidate_k": len(candidates),
            "candidate_table_map": source_map,
            "candidate_table_ids": candidate_table_ids,

            "column_queries": column_queries,
            "cell_queries": cell_queries,
            "retrieved_columns": all_retrieved_columns,
            "retrieved_cells": all_retrieved_cells,

            "solution": solution,
            "n_iter": n_iter,
            "init_prompt_token_count":
                init_prompt_token_count,

            "input_token_count": getattr(
                self,
                "total_input_token_count",
                0,
            ),
            "output_token_count": getattr(
                self,
                "total_output_token_count",
                0,
            ),
            "total_token_count": getattr(
                self,
                "total_token_count",
                (
                    getattr(
                        self,
                        "total_input_token_count",
                        0,
                    )
                    + getattr(
                        self,
                        "total_output_token_count",
                        0,
                    )
                ),
            ),
        }

        with open(
            log_path,
            "w",
            encoding="utf-8",
        ) as fp:
            json.dump(
                result,
                fp,
                ensure_ascii=False,
                indent=4,
            )

        with open(
            log_path.replace(".json", ".txt"),
            "w",
            encoding="utf-8",
        ) as fp:
            fp.write(prompt + solution)

        return result
